-- Outdaxius schema dump
-- Generated by reflecting the live dev database via SQLAlchemy (no pg_dump binary available).
-- Reflects the actual applied Alembic migrations, not the static ORM model declarations.
-- 25 tables

CREATE TABLE _migration_0001_dropped_memberships (
	id UUID, 
	team_id UUID, 
	user_id UUID, 
	joined_at TIMESTAMP WITH TIME ZONE, 
	team_role TEXT, 
	role_level SMALLINT, 
	archived_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE locations (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	display_name TEXT NOT NULL, 
	lat DOUBLE PRECISION NOT NULL, 
	lon DOUBLE PRECISION NOT NULL, 
	plus_code TEXT, 
	google_maps_url TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	source VARCHAR(16) DEFAULT 'manual'::character varying NOT NULL, 
	osm_id BIGINT, 
	geonames_id BIGINT, 
	wof_id BIGINT, 
	wikidata_id TEXT, 
	CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE tax_rates (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	country TEXT NOT NULL, 
	region TEXT, 
	rate NUMERIC(5, 2) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT tax_rates_pkey PRIMARY KEY (id)
);

CREATE TABLE types (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	type_name VARCHAR(100) NOT NULL, 
	experience_type VARCHAR(10) NOT NULL, 
	CONSTRAINT types_pkey PRIMARY KEY (id), 
	CONSTRAINT types_type_name_key UNIQUE NULLS DISTINCT (type_name)
);

CREATE TABLE users (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	display_name TEXT NOT NULL, 
	email TEXT NOT NULL, 
	password_hash TEXT NOT NULL, 
	tax_id TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	first_name TEXT, 
	last_name TEXT, 
	national_id TEXT, 
	passport_number TEXT, 
	phone TEXT, 
	profile_picture TEXT, 
	fiscal_data JSONB DEFAULT '{}'::jsonb, 
	profile JSONB DEFAULT '{}'::jsonb, 
	preferred_language TEXT, 
	is_active BOOLEAN NOT NULL, 
	role user_role DEFAULT 'client'::user_role NOT NULL, 
	birth_date DATE, 
	CONSTRAINT users_pkey PRIMARY KEY (id), 
	CONSTRAINT users_email_key UNIQUE NULLS DISTINCT (email), 
	CONSTRAINT users_national_id_key UNIQUE NULLS DISTINCT (national_id), 
	CONSTRAINT users_passport_number_key UNIQUE NULLS DISTINCT (passport_number)
);

CREATE TABLE audit_logs (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	user_id UUID, 
	action TEXT NOT NULL, 
	table_name TEXT NOT NULL, 
	record_id UUID, 
	details JSONB DEFAULT '{}'::jsonb, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id), 
	CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE company (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	name TEXT NOT NULL, 
	description TEXT, 
	createdby UUID NOT NULL, 
	createdat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updatedat TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	legal_representive TEXT, 
	legal_representive_text TEXT, 
	legal_representive_phone TEXT, 
	is_multinational BOOLEAN DEFAULT false NOT NULL, 
	legal_name TEXT, 
	trade_name TEXT, 
	incorporation_date DATE, 
	country TEXT, 
	currency VARCHAR(3) DEFAULT 'CLP'::character varying, 
	entity_type TEXT, 
	address TEXT, 
	license_tier VARCHAR(20) DEFAULT 'free'::character varying, 
	is_active BOOLEAN DEFAULT true, 
	subscription_expires_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT company_pkey PRIMARY KEY (id), 
	CONSTRAINT company_createdby_fkey FOREIGN KEY(createdby) REFERENCES users (id), 
	CONSTRAINT check_license_tier CHECK (license_tier::text = ANY (ARRAY['free'::character varying, 'basic'::character varying, 'pro'::character varying, 'enterprise'::character varying]::text[])), 
	CONSTRAINT ck_company_currency CHECK (currency::text ~ '^[A-Z]{3}$'::text)
);

CREATE TABLE payment_methods (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	user_id UUID, 
	type payment_method_type NOT NULL, 
	details JSONB DEFAULT '{}'::jsonb, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT payment_methods_pkey PRIMARY KEY (id), 
	CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE temporary_access_tokens (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	user_id UUID, 
	token TEXT NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	used BOOLEAN DEFAULT false, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT temporary_access_tokens_pkey PRIMARY KEY (id), 
	CONSTRAINT temporary_access_tokens_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT temporary_access_tokens_token_key UNIQUE NULLS DISTINCT (token)
);

CREATE TABLE company_members (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	companyid UUID NOT NULL, 
	userid UUID NOT NULL, 
	position TEXT NOT NULL, 
	joinedat DATE, 
	is_admin BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	CONSTRAINT company_members_pkey PRIMARY KEY (id), 
	CONSTRAINT company_members_companyid_fkey FOREIGN KEY(companyid) REFERENCES company (id) ON DELETE CASCADE, 
	CONSTRAINT company_members_userid_fkey FOREIGN KEY(userid) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE company_payment_accounts (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	company_id UUID NOT NULL, 
	provider TEXT NOT NULL, 
	external_account_id TEXT, 
	credentials_encrypted BYTEA NOT NULL, 
	charges_enabled BOOLEAN DEFAULT false NOT NULL, 
	currency VARCHAR(3) DEFAULT 'CLP'::character varying NOT NULL, 
	is_sandbox BOOLEAN DEFAULT true NOT NULL, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT company_payment_accounts_pkey PRIMARY KEY (id), 
	CONSTRAINT company_payment_accounts_company_id_fkey FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE CASCADE, 
	CONSTRAINT uq_payment_account_provider UNIQUE NULLS DISTINCT (company_id, provider), 
	CONSTRAINT ck_payment_accounts_provider CHECK (provider = ANY (ARRAY['flow'::text, 'stripe'::text, 'transbank'::text, 'mercadopago'::text]))
);

CREATE TABLE invitation_codes (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	code TEXT NOT NULL, 
	created_by UUID, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	used BOOLEAN DEFAULT false, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	status VARCHAR(20) DEFAULT 'pending'::character varying, 
	invited_email TEXT, 
	used_by UUID, 
	used_at TIMESTAMP WITH TIME ZONE, 
	company_id UUID NOT NULL, 
	CONSTRAINT invitation_codes_pkey PRIMARY KEY (id), 
	CONSTRAINT invitation_codes_company_id_fkey FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE CASCADE, 
	CONSTRAINT invitation_codes_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT invitation_codes_used_by_fkey FOREIGN KEY(used_by) REFERENCES users (id), 
	CONSTRAINT invitation_codes_code_key UNIQUE NULLS DISTINCT (code), 
	CONSTRAINT check_invitation_status CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])), 
	CONSTRAINT chk_invitation_status CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'expired'::character varying, 'revoked'::character varying]::text[]))
);

CREATE TABLE teams (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	name TEXT NOT NULL, 
	created_by UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	description TEXT, 
	company_id UUID NOT NULL, 
	archived_at TIMESTAMP WITH TIME ZONE, 
	succeeded_by_team_id UUID, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	CONSTRAINT teams_pkey PRIMARY KEY (id), 
	CONSTRAINT fk_company FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE CASCADE, 
	CONSTRAINT teams_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT teams_succeeded_by_team_id_fkey FOREIGN KEY(succeeded_by_team_id) REFERENCES teams (id)
);

CREATE TABLE activities (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	title TEXT NOT NULL, 
	description TEXT, 
	gallery JSONB DEFAULT '[]'::jsonb NOT NULL, 
	created_by UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	activity_type UUID, 
	location_id UUID, 
	guide_leader UUID, 
	team_id UUID, 
	is_shared BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT activities_pkey PRIMARY KEY (id), 
	CONSTRAINT activities_activity_type_fkey FOREIGN KEY(activity_type) REFERENCES types (id), 
	CONSTRAINT activities_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT activities_guide_leader_fkey FOREIGN KEY(guide_leader) REFERENCES users (id), 
	CONSTRAINT activities_location_id_fkey FOREIGN KEY(location_id) REFERENCES locations (id) ON DELETE SET NULL, 
	CONSTRAINT activities_team_id_fkey FOREIGN KEY(team_id) REFERENCES teams (id)
);

CREATE TABLE membership_requests (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	direction TEXT NOT NULL, 
	team_id UUID NOT NULL, 
	company_id UUID NOT NULL, 
	target_user_id UUID, 
	target_email TEXT, 
	offered_level SMALLINT DEFAULT 4 NOT NULL, 
	created_by UUID NOT NULL, 
	on_behalf_of_company_id UUID, 
	target_consent TEXT DEFAULT 'not_required'::text NOT NULL, 
	message TEXT, 
	status TEXT DEFAULT 'pending'::text NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	responded_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT membership_requests_pkey PRIMARY KEY (id), 
	CONSTRAINT membership_requests_company_id_fkey FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE CASCADE, 
	CONSTRAINT membership_requests_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT membership_requests_on_behalf_of_company_id_fkey FOREIGN KEY(on_behalf_of_company_id) REFERENCES company (id), 
	CONSTRAINT membership_requests_target_user_id_fkey FOREIGN KEY(target_user_id) REFERENCES users (id), 
	CONSTRAINT membership_requests_team_id_fkey FOREIGN KEY(team_id) REFERENCES teams (id) ON DELETE CASCADE, 
	CONSTRAINT ck_membership_requests_consent CHECK (target_consent = ANY (ARRAY['not_required'::text, 'pending'::text, 'granted'::text, 'refused'::text])), 
	CONSTRAINT ck_membership_requests_direction CHECK (direction = ANY (ARRAY['invitation'::text, 'application'::text])), 
	CONSTRAINT ck_membership_requests_level CHECK (offered_level >= 1 AND offered_level <= 4), 
	CONSTRAINT ck_membership_requests_status CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text, 'expired'::text])), 
	CONSTRAINT ck_membership_requests_target CHECK (target_user_id IS NOT NULL OR target_email IS NOT NULL)
);

CREATE TABLE programs (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	title TEXT NOT NULL, 
	description TEXT, 
	gallery JSONB DEFAULT '[]'::jsonb NOT NULL, 
	min_activities INTEGER DEFAULT 2, 
	created_by UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	program_type UUID NOT NULL, 
	guide_leader UUID, 
	team_id UUID, 
	is_shared BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT programs_pkey PRIMARY KEY (id), 
	CONSTRAINT programs_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT programs_guide_leader_fkey FOREIGN KEY(guide_leader) REFERENCES users (id), 
	CONSTRAINT programs_program_type_fkey FOREIGN KEY(program_type) REFERENCES types (id), 
	CONSTRAINT programs_team_id_fkey FOREIGN KEY(team_id) REFERENCES teams (id)
);

CREATE TABLE team_members (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	team_id UUID, 
	user_id UUID, 
	joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	role_level SMALLINT DEFAULT 4 NOT NULL, 
	CONSTRAINT team_members_pkey PRIMARY KEY (id), 
	CONSTRAINT team_members_team_id_fkey FOREIGN KEY(team_id) REFERENCES teams (id) ON DELETE CASCADE, 
	CONSTRAINT team_members_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT uq_team_members_user UNIQUE NULLS DISTINCT (user_id), 
	CONSTRAINT ck_team_members_role_level CHECK (role_level >= 1 AND role_level <= 4)
);

CREATE TABLE program_schedules (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	program_id UUID, 
	start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	price NUMERIC(12, 2) DEFAULT 0 NOT NULL, 
	status VARCHAR(20) DEFAULT 'pending'::character varying NOT NULL, 
	min_participants INTEGER, 
	max_participants INTEGER, 
	selling_company_id UUID, 
	settlement_discount_type TEXT, 
	settlement_discount_value NUMERIC(12, 2), 
	CONSTRAINT schedules_pkey PRIMARY KEY (id), 
	CONSTRAINT program_schedules_selling_company_id_fkey FOREIGN KEY(selling_company_id) REFERENCES company (id), 
	CONSTRAINT schedules_program_id_fkey FOREIGN KEY(program_id) REFERENCES programs (id) ON DELETE CASCADE, 
	CONSTRAINT ck_program_schedules_settlement_type CHECK (settlement_discount_type IS NULL OR (settlement_discount_type = ANY (ARRAY['percent'::text, 'fixed'::text])))
);

CREATE TABLE programactivities (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	program_id UUID, 
	activity_id UUID, 
	CONSTRAINT programactivities_pkey PRIMARY KEY (id), 
	CONSTRAINT programactivities_activity_id_fkey FOREIGN KEY(activity_id) REFERENCES activities (id) ON DELETE CASCADE, 
	CONSTRAINT programactivities_program_id_fkey FOREIGN KEY(program_id) REFERENCES programs (id) ON DELETE CASCADE
);

CREATE TABLE reviews (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	user_id UUID, 
	program_id UUID, 
	rating INTEGER, 
	comment TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT reviews_pkey PRIMARY KEY (id), 
	CONSTRAINT reviews_program_id_fkey FOREIGN KEY(program_id) REFERENCES programs (id) ON DELETE CASCADE, 
	CONSTRAINT reviews_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE activity_schedules (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	program_schedule_id UUID, 
	activity_id UUID, 
	start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	price NUMERIC(10, 2), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	status VARCHAR(20) DEFAULT 'pending'::character varying NOT NULL, 
	min_participants INTEGER, 
	max_participants INTEGER, 
	selling_company_id UUID, 
	CONSTRAINT activity_schedules_pkey PRIMARY KEY (id), 
	CONSTRAINT activity_schedules_activity_id_fkey FOREIGN KEY(activity_id) REFERENCES activities (id) ON DELETE CASCADE, 
	CONSTRAINT activity_schedules_program_schedule_id_fkey FOREIGN KEY(program_schedule_id) REFERENCES program_schedules (id) ON DELETE CASCADE, 
	CONSTRAINT activity_schedules_selling_company_id_fkey FOREIGN KEY(selling_company_id) REFERENCES company (id)
);

CREATE TABLE assignments (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	activity_schedule_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	home_team_id UUID NOT NULL, 
	home_company_id UUID NOT NULL, 
	is_leader BOOLEAN DEFAULT false NOT NULL, 
	status TEXT DEFAULT 'proposed'::text NOT NULL, 
	proposed_by UUID NOT NULL, 
	proposed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	responded_at TIMESTAMP WITH TIME ZONE, 
	decline_reason TEXT, 
	CONSTRAINT assignments_pkey PRIMARY KEY (id), 
	CONSTRAINT assignments_activity_schedule_id_fkey FOREIGN KEY(activity_schedule_id) REFERENCES activity_schedules (id) ON DELETE CASCADE, 
	CONSTRAINT assignments_home_company_id_fkey FOREIGN KEY(home_company_id) REFERENCES company (id), 
	CONSTRAINT assignments_home_team_id_fkey FOREIGN KEY(home_team_id) REFERENCES teams (id), 
	CONSTRAINT assignments_proposed_by_fkey FOREIGN KEY(proposed_by) REFERENCES users (id), 
	CONSTRAINT assignments_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT uq_assignment_once UNIQUE NULLS DISTINCT (activity_schedule_id, user_id), 
	CONSTRAINT ck_assignments_status CHECK (status = ANY (ARRAY['proposed'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text]))
);

CREATE TABLE bookings (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	user_id UUID, 
	program_schedule_id UUID, 
	status booking_status DEFAULT 'pending'::booking_status, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	attendance_status attendance_status DEFAULT 'not_attended'::attendance_status NOT NULL, 
	activity_schedule_id UUID, 
	participants_count INTEGER DEFAULT 1 NOT NULL, 
	participants JSONB DEFAULT '[]'::jsonb NOT NULL, 
	cancelled_at TIMESTAMP WITH TIME ZONE, 
	cancellation_fee NUMERIC(12, 2) DEFAULT 0, 
	cancelled_by UUID, 
	cancelled_by_party TEXT, 
	cancellation_reason TEXT, 
	refund_amount NUMERIC(12, 2), 
	refund_status TEXT, 
	refund_reference TEXT, 
	policy_snapshot JSONB DEFAULT '{}'::jsonb NOT NULL, 
	CONSTRAINT bookings_pkey PRIMARY KEY (id), 
	CONSTRAINT bookings_activity_schedule_id_fkey FOREIGN KEY(activity_schedule_id) REFERENCES activity_schedules (id) ON DELETE CASCADE, 
	CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY(cancelled_by) REFERENCES users (id), 
	CONSTRAINT bookings_schedule_id_fkey FOREIGN KEY(program_schedule_id) REFERENCES program_schedules (id), 
	CONSTRAINT bookings_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT ck_bookings_cancelled_party CHECK (cancelled_by_party IS NULL OR (cancelled_by_party = ANY (ARRAY['client'::text, 'vendor'::text, 'system'::text]))), 
	CONSTRAINT ck_bookings_refund_status CHECK (refund_status IS NULL OR (refund_status = ANY (ARRAY['not_required'::text, 'pending'::text, 'succeeded'::text, 'failed'::text, 'manual'::text])))
);

CREATE TABLE payments (
	id UUID DEFAULT uuid_generate_v4() NOT NULL, 
	booking_id UUID, 
	method_id UUID, 
	amount NUMERIC(12, 2) NOT NULL, 
	currency VARCHAR(3) DEFAULT 'USD'::text NOT NULL, 
	status payment_status DEFAULT 'pending'::payment_status, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	tax_rate_id UUID, 
	voucher_url TEXT, 
	reference TEXT, 
	provider TEXT, 
	provider_ref TEXT, 
	CONSTRAINT payments_pkey PRIMARY KEY (id), 
	CONSTRAINT payments_booking_id_fkey FOREIGN KEY(booking_id) REFERENCES bookings (id) ON DELETE CASCADE, 
	CONSTRAINT payments_method_id_fkey FOREIGN KEY(method_id) REFERENCES payment_methods (id), 
	CONSTRAINT payments_tax_rate_id_fkey FOREIGN KEY(tax_rate_id) REFERENCES tax_rates (id) ON DELETE SET NULL, 
	CONSTRAINT ck_payments_currency CHECK (currency::text ~ '^[A-Z]{3}$'::text)
);

-- Indexes
CREATE INDEX idx_company_members_user ON company_members (userid);
CREATE INDEX idx_company_members_company ON company_members (companyid);
CREATE INDEX idx_invitation_codes_company ON invitation_codes (company_id);
CREATE INDEX idx_invitation_codes_email ON invitation_codes (invited_email);
CREATE INDEX idx_invitation_codes_status_expires ON invitation_codes (status, expires_at) WHERE ((status)::text = 'pending'::text);
CREATE INDEX idx_invitation_codes_code ON invitation_codes (code);
CREATE INDEX idx_invitation_codes_status ON invitation_codes (status);
CREATE INDEX idx_activities_team ON activities (team_id);
CREATE UNIQUE INDEX uq_membership_requests_pending ON membership_requests (team_id, target_user_id) WHERE ((status = 'pending'::text) AND (target_user_id IS NOT NULL));
CREATE INDEX idx_membership_requests_target ON membership_requests (target_user_id);
CREATE INDEX idx_programs_team ON programs (team_id);
CREATE UNIQUE INDEX uq_team_single_master ON team_members (team_id) WHERE (role_level = 1);
CREATE INDEX idx_team_members_team ON team_members (team_id);
CREATE INDEX idx_program_schedules_selling ON program_schedules (selling_company_id);
CREATE UNIQUE INDEX uq_assignment_single_leader ON assignments (activity_schedule_id) WHERE (is_leader AND (status = ANY (ARRAY['proposed'::text, 'accepted'::text])));
CREATE INDEX idx_assignments_company ON assignments (home_company_id);
CREATE INDEX idx_assignments_user ON assignments (user_id);
CREATE UNIQUE INDEX uq_booking_user_activity ON bookings (user_id, activity_schedule_id) WHERE (activity_schedule_id IS NOT NULL);
CREATE UNIQUE INDEX uq_booking_user_program ON bookings (user_id, program_schedule_id) WHERE (program_schedule_id IS NOT NULL);
CREATE UNIQUE INDEX uq_payments_provider_ref ON payments (provider, provider_ref) WHERE (provider_ref IS NOT NULL);
