-- Outdaxius schema dump
-- Generated by scripts/dump_schema.py (pg_dump --schema-only).
-- Regenerate this whenever a migration lands:  python -m scripts.dump_schema
--
-- This file is the starting point for a brand-new database: `alembic upgrade head`
-- alone cannot build one, because 0000_baseline is a no-op standing for a schema that
-- already existed. See scripts/bootstrap_schema.py.
-- Alembic revision: 0006_demo_payment_provider

--
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: attendance_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.attendance_status AS ENUM (
    'not_attended',
    'attended',
    'no_show'
);


--
-- Name: booking_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.booking_status AS ENUM (
    'pending',
    'confirmed',
    'cancelled'
);


--
-- Name: payment_method_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.payment_method_type AS ENUM (
    'card',
    'bank_transfer',
    'cash',
    'other'
);


--
-- Name: payment_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.payment_status AS ENUM (
    'pending',
    'succeeded',
    'failed',
    'refunded',
    'partially_refunded'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'guide',
    'client'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _migration_0001_dropped_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._migration_0001_dropped_memberships (
    id uuid,
    team_id uuid,
    user_id uuid,
    joined_at timestamp with time zone,
    team_role text,
    role_level smallint,
    archived_at timestamp with time zone
);


--
-- Name: activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activities (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title text NOT NULL,
    description text,
    gallery jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    activity_type uuid,
    location_id uuid,
    guide_leader uuid,
    team_id uuid,
    is_shared boolean DEFAULT false NOT NULL
);


--
-- Name: activity_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_schedules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    program_schedule_id uuid,
    activity_id uuid,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    price numeric(10,2),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    min_participants integer,
    max_participants integer,
    selling_company_id uuid
);


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assignments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    activity_schedule_id uuid NOT NULL,
    user_id uuid NOT NULL,
    home_team_id uuid NOT NULL,
    home_company_id uuid NOT NULL,
    is_leader boolean DEFAULT false NOT NULL,
    status text DEFAULT 'proposed'::text NOT NULL,
    proposed_by uuid NOT NULL,
    proposed_at timestamp with time zone DEFAULT now() NOT NULL,
    responded_at timestamp with time zone,
    decline_reason text,
    CONSTRAINT ck_assignments_status CHECK ((status = ANY (ARRAY['proposed'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text])))
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    action text NOT NULL,
    table_name text NOT NULL,
    record_id uuid,
    details jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    program_schedule_id uuid,
    status public.booking_status DEFAULT 'pending'::public.booking_status,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    attendance_status public.attendance_status DEFAULT 'not_attended'::public.attendance_status NOT NULL,
    activity_schedule_id uuid,
    participants_count integer DEFAULT 1 NOT NULL,
    participants jsonb DEFAULT '[]'::jsonb NOT NULL,
    cancelled_at timestamp with time zone,
    cancellation_fee numeric(12,2) DEFAULT 0,
    cancelled_by uuid,
    cancelled_by_party text,
    cancellation_reason text,
    refund_amount numeric(12,2),
    refund_status text,
    refund_reference text,
    policy_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_bookings_cancelled_party CHECK (((cancelled_by_party IS NULL) OR (cancelled_by_party = ANY (ARRAY['client'::text, 'vendor'::text, 'system'::text])))),
    CONSTRAINT ck_bookings_refund_status CHECK (((refund_status IS NULL) OR (refund_status = ANY (ARRAY['not_required'::text, 'pending'::text, 'succeeded'::text, 'failed'::text, 'manual'::text]))))
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text,
    createdby uuid NOT NULL,
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now(),
    legal_representive text,
    legal_representive_text text,
    legal_representive_phone text,
    is_multinational boolean DEFAULT false NOT NULL,
    legal_name text,
    trade_name text,
    incorporation_date date,
    country text,
    currency character varying(3) DEFAULT 'CLP'::character varying,
    entity_type text,
    address text,
    license_tier character varying(20) DEFAULT 'free'::character varying,
    is_active boolean DEFAULT true,
    subscription_expires_at timestamp with time zone,
    CONSTRAINT check_license_tier CHECK (((license_tier)::text = ANY (ARRAY[('free'::character varying)::text, ('basic'::character varying)::text, ('pro'::character varying)::text, ('enterprise'::character varying)::text]))),
    CONSTRAINT ck_company_currency CHECK (((currency)::text ~ '^[A-Z]{3}$'::text))
);


--
-- Name: company_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    companyid uuid NOT NULL,
    userid uuid NOT NULL,
    "position" text NOT NULL,
    joinedat date,
    is_admin boolean NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: company_payment_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_payment_accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    provider text NOT NULL,
    external_account_id text,
    credentials_encrypted bytea NOT NULL,
    charges_enabled boolean DEFAULT false NOT NULL,
    currency character varying(3) DEFAULT 'CLP'::character varying NOT NULL,
    is_sandbox boolean DEFAULT true NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_payment_accounts_provider CHECK ((provider = ANY (ARRAY['flow'::text, 'stripe'::text, 'transbank'::text, 'mercadopago'::text, 'demo'::text])))
);


--
-- Name: invitation_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitation_codes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    code text NOT NULL,
    created_by uuid,
    expires_at timestamp with time zone,
    used boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    status character varying(20) DEFAULT 'pending'::character varying,
    invited_email text,
    used_by uuid,
    used_at timestamp with time zone,
    company_id uuid NOT NULL,
    CONSTRAINT check_invitation_status CHECK (((status)::text = ANY (ARRAY[('pending'::character varying)::text, ('accepted'::character varying)::text, ('rejected'::character varying)::text, ('expired'::character varying)::text]))),
    CONSTRAINT chk_invitation_status CHECK (((status)::text = ANY (ARRAY[('pending'::character varying)::text, ('accepted'::character varying)::text, ('expired'::character varying)::text, ('revoked'::character varying)::text])))
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name text NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    plus_code text,
    google_maps_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    source character varying(16) DEFAULT 'manual'::character varying NOT NULL,
    osm_id bigint,
    geonames_id bigint,
    wof_id bigint,
    wikidata_id text
);


--
-- Name: membership_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    direction text NOT NULL,
    team_id uuid NOT NULL,
    company_id uuid NOT NULL,
    target_user_id uuid,
    target_email text,
    offered_level smallint DEFAULT 4 NOT NULL,
    created_by uuid NOT NULL,
    on_behalf_of_company_id uuid,
    target_consent text DEFAULT 'not_required'::text NOT NULL,
    message text,
    status text DEFAULT 'pending'::text NOT NULL,
    expires_at timestamp with time zone,
    responded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_membership_requests_consent CHECK ((target_consent = ANY (ARRAY['not_required'::text, 'pending'::text, 'granted'::text, 'refused'::text]))),
    CONSTRAINT ck_membership_requests_direction CHECK ((direction = ANY (ARRAY['invitation'::text, 'application'::text]))),
    CONSTRAINT ck_membership_requests_level CHECK (((offered_level >= 1) AND (offered_level <= 4))),
    CONSTRAINT ck_membership_requests_status CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text, 'expired'::text]))),
    CONSTRAINT ck_membership_requests_target CHECK (((target_user_id IS NOT NULL) OR (target_email IS NOT NULL)))
);


--
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_methods (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    type public.payment_method_type NOT NULL,
    details jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    booking_id uuid,
    method_id uuid,
    amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::text NOT NULL,
    status public.payment_status DEFAULT 'pending'::public.payment_status,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    tax_rate_id uuid,
    voucher_url text,
    reference text,
    provider text,
    provider_ref text,
    CONSTRAINT ck_payments_currency CHECK (((currency)::text ~ '^[A-Z]{3}$'::text))
);


--
-- Name: program_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program_schedules (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    program_id uuid,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    price numeric(12,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    min_participants integer,
    max_participants integer,
    selling_company_id uuid,
    settlement_discount_type text,
    settlement_discount_value numeric(12,2),
    CONSTRAINT ck_program_schedules_settlement_type CHECK (((settlement_discount_type IS NULL) OR (settlement_discount_type = ANY (ARRAY['percent'::text, 'fixed'::text]))))
);


--
-- Name: programactivities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programactivities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    program_id uuid,
    activity_id uuid
);


--
-- Name: programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title text NOT NULL,
    description text,
    gallery jsonb DEFAULT '[]'::jsonb NOT NULL,
    min_activities integer DEFAULT 2,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    program_type uuid NOT NULL,
    guide_leader uuid,
    team_id uuid,
    is_shared boolean DEFAULT false NOT NULL
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    program_id uuid,
    rating integer,
    comment text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: tax_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_rates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    country text NOT NULL,
    region text,
    rate numeric(5,2) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: team_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    team_id uuid,
    user_id uuid,
    joined_at timestamp with time zone DEFAULT now(),
    role_level smallint DEFAULT 4 NOT NULL,
    CONSTRAINT ck_team_members_role_level CHECK (((role_level >= 1) AND (role_level <= 4)))
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    description text,
    company_id uuid NOT NULL,
    archived_at timestamp with time zone,
    succeeded_by_team_id uuid,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: temporary_access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.temporary_access_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.types (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    type_name character varying(100) NOT NULL,
    experience_type character varying(10) NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    display_name text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    tax_id text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    first_name text,
    last_name text,
    national_id text,
    passport_number text,
    phone text,
    profile_picture text,
    fiscal_data jsonb DEFAULT '{}'::jsonb,
    profile jsonb DEFAULT '{}'::jsonb,
    preferred_language text,
    is_active boolean NOT NULL,
    role public.user_role DEFAULT 'client'::public.user_role NOT NULL,
    birth_date date
);


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: activity_schedules activity_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_schedules
    ADD CONSTRAINT activity_schedules_pkey PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: company_members company_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_members
    ADD CONSTRAINT company_members_pkey PRIMARY KEY (id);


--
-- Name: company_payment_accounts company_payment_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_payment_accounts
    ADD CONSTRAINT company_payment_accounts_pkey PRIMARY KEY (id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: invitation_codes invitation_codes_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_codes
    ADD CONSTRAINT invitation_codes_code_key UNIQUE (code);


--
-- Name: invitation_codes invitation_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_codes
    ADD CONSTRAINT invitation_codes_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: membership_requests membership_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_pkey PRIMARY KEY (id);


--
-- Name: payment_methods payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: programactivities programactivities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programactivities
    ADD CONSTRAINT programactivities_pkey PRIMARY KEY (id);


--
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: program_schedules schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (id);


--
-- Name: tax_rates tax_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rates
    ADD CONSTRAINT tax_rates_pkey PRIMARY KEY (id);


--
-- Name: team_members team_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: temporary_access_tokens temporary_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_access_tokens
    ADD CONSTRAINT temporary_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: temporary_access_tokens temporary_access_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_access_tokens
    ADD CONSTRAINT temporary_access_tokens_token_key UNIQUE (token);


--
-- Name: types types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_pkey PRIMARY KEY (id);


--
-- Name: types types_type_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_type_name_key UNIQUE (type_name);


--
-- Name: assignments uq_assignment_once; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT uq_assignment_once UNIQUE (activity_schedule_id, user_id);


--
-- Name: company_payment_accounts uq_payment_account_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_payment_accounts
    ADD CONSTRAINT uq_payment_account_provider UNIQUE (company_id, provider);


--
-- Name: team_members uq_team_members_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT uq_team_members_user UNIQUE (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_national_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_national_id_key UNIQUE (national_id);


--
-- Name: users users_passport_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_passport_number_key UNIQUE (passport_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_activities_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activities_team ON public.activities USING btree (team_id);


--
-- Name: idx_assignments_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assignments_company ON public.assignments USING btree (home_company_id);


--
-- Name: idx_assignments_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assignments_user ON public.assignments USING btree (user_id);


--
-- Name: idx_company_members_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_members_company ON public.company_members USING btree (companyid);


--
-- Name: idx_company_members_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_members_user ON public.company_members USING btree (userid);


--
-- Name: idx_invitation_codes_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_codes_code ON public.invitation_codes USING btree (code);


--
-- Name: idx_invitation_codes_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_codes_company ON public.invitation_codes USING btree (company_id);


--
-- Name: idx_invitation_codes_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_codes_email ON public.invitation_codes USING btree (invited_email);


--
-- Name: idx_invitation_codes_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_codes_status ON public.invitation_codes USING btree (status);


--
-- Name: idx_invitation_codes_status_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_codes_status_expires ON public.invitation_codes USING btree (status, expires_at) WHERE ((status)::text = 'pending'::text);


--
-- Name: idx_membership_requests_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_requests_target ON public.membership_requests USING btree (target_user_id);


--
-- Name: idx_program_schedules_selling; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_program_schedules_selling ON public.program_schedules USING btree (selling_company_id);


--
-- Name: idx_programs_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_programs_team ON public.programs USING btree (team_id);


--
-- Name: idx_team_members_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_team_members_team ON public.team_members USING btree (team_id);


--
-- Name: uq_assignment_single_leader; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_assignment_single_leader ON public.assignments USING btree (activity_schedule_id) WHERE (is_leader AND (status = ANY (ARRAY['proposed'::text, 'accepted'::text])));


--
-- Name: uq_booking_user_activity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_booking_user_activity ON public.bookings USING btree (user_id, activity_schedule_id) WHERE (activity_schedule_id IS NOT NULL);


--
-- Name: uq_booking_user_program; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_booking_user_program ON public.bookings USING btree (user_id, program_schedule_id) WHERE (program_schedule_id IS NOT NULL);


--
-- Name: uq_membership_requests_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_membership_requests_pending ON public.membership_requests USING btree (team_id, target_user_id) WHERE ((status = 'pending'::text) AND (target_user_id IS NOT NULL));


--
-- Name: uq_payments_provider_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_payments_provider_ref ON public.payments USING btree (provider, provider_ref) WHERE (provider_ref IS NOT NULL);


--
-- Name: uq_team_single_master; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_team_single_master ON public.team_members USING btree (team_id) WHERE (role_level = 1);


--
-- Name: activities activities_activity_type_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_activity_type_fkey FOREIGN KEY (activity_type) REFERENCES public.types(id);


--
-- Name: activities activities_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: activities activities_guide_leader_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_guide_leader_fkey FOREIGN KEY (guide_leader) REFERENCES public.users(id);


--
-- Name: activities activities_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- Name: activities activities_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: activity_schedules activity_schedules_activity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_schedules
    ADD CONSTRAINT activity_schedules_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id) ON DELETE CASCADE;


--
-- Name: activity_schedules activity_schedules_program_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_schedules
    ADD CONSTRAINT activity_schedules_program_schedule_id_fkey FOREIGN KEY (program_schedule_id) REFERENCES public.program_schedules(id) ON DELETE CASCADE;


--
-- Name: activity_schedules activity_schedules_selling_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_schedules
    ADD CONSTRAINT activity_schedules_selling_company_id_fkey FOREIGN KEY (selling_company_id) REFERENCES public.company(id);


--
-- Name: assignments assignments_activity_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_activity_schedule_id_fkey FOREIGN KEY (activity_schedule_id) REFERENCES public.activity_schedules(id) ON DELETE CASCADE;


--
-- Name: assignments assignments_home_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_home_company_id_fkey FOREIGN KEY (home_company_id) REFERENCES public.company(id);


--
-- Name: assignments assignments_home_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id);


--
-- Name: assignments assignments_proposed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_proposed_by_fkey FOREIGN KEY (proposed_by) REFERENCES public.users(id);


--
-- Name: assignments assignments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: audit_logs audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookings bookings_activity_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_activity_schedule_id_fkey FOREIGN KEY (activity_schedule_id) REFERENCES public.activity_schedules(id) ON DELETE CASCADE;


--
-- Name: bookings bookings_cancelled_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id);


--
-- Name: bookings bookings_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_schedule_id_fkey FOREIGN KEY (program_schedule_id) REFERENCES public.program_schedules(id);


--
-- Name: bookings bookings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: company company_createdby_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_createdby_fkey FOREIGN KEY (createdby) REFERENCES public.users(id);


--
-- Name: company_members company_members_companyid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_members
    ADD CONSTRAINT company_members_companyid_fkey FOREIGN KEY (companyid) REFERENCES public.company(id) ON DELETE CASCADE;


--
-- Name: company_members company_members_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_members
    ADD CONSTRAINT company_members_userid_fkey FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: company_payment_accounts company_payment_accounts_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_payment_accounts
    ADD CONSTRAINT company_payment_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE;


--
-- Name: teams fk_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE;


--
-- Name: invitation_codes invitation_codes_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_codes
    ADD CONSTRAINT invitation_codes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE;


--
-- Name: invitation_codes invitation_codes_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_codes
    ADD CONSTRAINT invitation_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: invitation_codes invitation_codes_used_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_codes
    ADD CONSTRAINT invitation_codes_used_by_fkey FOREIGN KEY (used_by) REFERENCES public.users(id);


--
-- Name: membership_requests membership_requests_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE;


--
-- Name: membership_requests membership_requests_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: membership_requests membership_requests_on_behalf_of_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_on_behalf_of_company_id_fkey FOREIGN KEY (on_behalf_of_company_id) REFERENCES public.company(id);


--
-- Name: membership_requests membership_requests_target_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id);


--
-- Name: membership_requests membership_requests_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_requests
    ADD CONSTRAINT membership_requests_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: payment_methods payment_methods_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payments payments_booking_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: payments payments_method_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_method_id_fkey FOREIGN KEY (method_id) REFERENCES public.payment_methods(id);


--
-- Name: payments payments_tax_rate_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_tax_rate_id_fkey FOREIGN KEY (tax_rate_id) REFERENCES public.tax_rates(id) ON DELETE SET NULL;


--
-- Name: program_schedules program_schedules_selling_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_schedules
    ADD CONSTRAINT program_schedules_selling_company_id_fkey FOREIGN KEY (selling_company_id) REFERENCES public.company(id);


--
-- Name: programactivities programactivities_activity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programactivities
    ADD CONSTRAINT programactivities_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id) ON DELETE CASCADE;


--
-- Name: programactivities programactivities_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programactivities
    ADD CONSTRAINT programactivities_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: programs programs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: programs programs_guide_leader_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_guide_leader_fkey FOREIGN KEY (guide_leader) REFERENCES public.users(id);


--
-- Name: programs programs_program_type_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_program_type_fkey FOREIGN KEY (program_type) REFERENCES public.types(id);


--
-- Name: programs programs_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: reviews reviews_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: reviews reviews_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: program_schedules schedules_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_schedules
    ADD CONSTRAINT schedules_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: team_members team_members_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: team_members team_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: teams teams_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: teams teams_succeeded_by_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_succeeded_by_team_id_fkey FOREIGN KEY (succeeded_by_team_id) REFERENCES public.teams(id);


--
-- Name: temporary_access_tokens temporary_access_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_access_tokens
    ADD CONSTRAINT temporary_access_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
--
