-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    gallery jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_by uuid NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    activity_type uuid,
    location_id uuid,
    guide_leader uuid,
    CONSTRAINT activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.activity_schedules
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    program_schedule_id uuid,
    activity_id uuid,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    price numeric(10, 2),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    min_participants integer,
    max_participants integer,
    CONSTRAINT activity_schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    action text COLLATE pg_catalog."default" NOT NULL,
    table_name text COLLATE pg_catalog."default" NOT NULL,
    record_id uuid,
    details jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    program_schedule_id uuid,
    status booking_status DEFAULT 'pending'::booking_status,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    attendance_status attendance_status DEFAULT 'not_attended'::attendance_status,
    activity_schedule_id uuid,
    participants_count integer NOT NULL DEFAULT 1,
    participants jsonb NOT NULL DEFAULT '[]'::jsonb,
    cancelled_at timestamp without time zone,
    cancellation_fee numeric(12, 2) DEFAULT 0,
    CONSTRAINT bookings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    createdby uuid NOT NULL,
    createdat timestamp without time zone NOT NULL DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    legal_representive text COLLATE pg_catalog."default" NOT NULL,
    legal_representive_text text COLLATE pg_catalog."default" NOT NULL,
    legal_representive_phone text COLLATE pg_catalog."default" NOT NULL,
    is_multinational boolean NOT NULL DEFAULT false,
    legal_name text COLLATE pg_catalog."default" NOT NULL,
    trade_name text COLLATE pg_catalog."default" NOT NULL,
    incorporation_date date NOT NULL,
    country text COLLATE pg_catalog."default" NOT NULL,
    currency "char" NOT NULL,
    entity_type text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    license_tier character varying(20) COLLATE pg_catalog."default" DEFAULT 'free'::character varying,
    max_guides integer DEFAULT 5,
    is_active boolean DEFAULT true,
    subscription_expires_at timestamp without time zone,
    CONSTRAINT company_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_members
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    companyid uuid NOT NULL,
    userid uuid NOT NULL,
    "position" text COLLATE pg_catalog."default" NOT NULL,
    joinedat date,
    is_admin boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT company_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.invitation_codes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    code text COLLATE pg_catalog."default" NOT NULL,
    created_by uuid,
    expires_at timestamp without time zone,
    used boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    invited_email text COLLATE pg_catalog."default",
    used_by uuid,
    used_at timestamp without time zone,
    company_id uuid NOT NULL,
    CONSTRAINT invitation_codes_pkey PRIMARY KEY (id),
    CONSTRAINT invitation_codes_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    display_name text COLLATE pg_catalog."default" NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    plus_code text COLLATE pg_catalog."default",
    google_maps_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    source character varying(16) COLLATE pg_catalog."default" NOT NULL DEFAULT 'manual'::character varying,
    osm_id bigint,
    geonames_id bigint,
    wof_id bigint,
    wikidata_id text COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_methods
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    type payment_method_type NOT NULL,
    details jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    booking_id uuid,
    method_id uuid,
    amount numeric(12, 2) NOT NULL,
    currency text COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::text,
    status payment_status DEFAULT 'pending'::payment_status,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    tax_rate_id uuid,
    voucher_url text COLLATE pg_catalog."default",
    reference text COLLATE pg_catalog."default",
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.program_schedules
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    program_id uuid,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    price numeric(12, 2) NOT NULL DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    min_participants integer,
    max_participants integer,
    CONSTRAINT schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.programactivities
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    program_id uuid,
    activity_id uuid,
    CONSTRAINT programactivities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.programs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    gallery jsonb NOT NULL DEFAULT '[]'::jsonb,
    min_activities integer DEFAULT 2,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    program_type uuid NOT NULL,
    guide_leader uuid,
    CONSTRAINT programs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    program_id uuid,
    rating integer,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    permission_id uuid,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tax_rates
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    country text COLLATE pg_catalog."default" NOT NULL,
    region text COLLATE pg_catalog."default",
    rate numeric(5, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT tax_rates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team_members
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    team_id uuid,
    user_id uuid,
    joined_at timestamp without time zone DEFAULT now(),
    team_role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'day_guide'::text,
    CONSTRAINT team_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default" NOT NULL,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    description text COLLATE pg_catalog."default",
    company_id uuid NOT NULL,
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.temporary_access_tokens
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT temporary_access_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT temporary_access_tokens_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.types
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    experience_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT types_pkey PRIMARY KEY (id),
    CONSTRAINT types_type_name_key UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    display_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    tax_id text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    national_id text COLLATE pg_catalog."default",
    passport_number text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    profile_picture text COLLATE pg_catalog."default",
    fiscal_data jsonb DEFAULT '{}'::jsonb,
    profile jsonb DEFAULT '{}'::jsonb,
    preferred_language text COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    role user_role NOT NULL DEFAULT 'user'::user_role,
    birth_date date,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_national_id_key UNIQUE (national_id),
    CONSTRAINT users_passport_number_key UNIQUE (passport_number)
);

ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_activity_type_fkey FOREIGN KEY (activity_type)
    REFERENCES public.types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_guide_leader_fkey FOREIGN KEY (guide_leader)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.activity_schedules
    ADD CONSTRAINT activity_schedules_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.activity_schedules
    ADD CONSTRAINT activity_schedules_program_schedule_id_fkey FOREIGN KEY (program_schedule_id)
    REFERENCES public.program_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_activity_schedule_id_fkey FOREIGN KEY (activity_schedule_id)
    REFERENCES public.activity_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_schedule_id_fkey FOREIGN KEY (program_schedule_id)
    REFERENCES public.program_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.company
    ADD CONSTRAINT company_createdby_fkey FOREIGN KEY (createdby)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.company_members
    ADD CONSTRAINT company_members_companyid_fkey FOREIGN KEY (companyid)
    REFERENCES public.company (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_company_members_company
    ON public.company_members(companyid);


ALTER TABLE IF EXISTS public.company_members
    ADD CONSTRAINT company_members_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_company_members_user
    ON public.company_members(userid);


ALTER TABLE IF EXISTS public.invitation_codes
    ADD CONSTRAINT invitation_codes_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.company (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_invitation_codes_company
    ON public.invitation_codes(company_id);


ALTER TABLE IF EXISTS public.invitation_codes
    ADD CONSTRAINT invitation_codes_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invitation_codes
    ADD CONSTRAINT invitation_codes_used_by_fkey FOREIGN KEY (used_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_methods
    ADD CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_method_id_fkey FOREIGN KEY (method_id)
    REFERENCES public.payment_methods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_tax_rate_id_fkey FOREIGN KEY (tax_rate_id)
    REFERENCES public.tax_rates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.program_schedules
    ADD CONSTRAINT schedules_program_id_fkey FOREIGN KEY (program_id)
    REFERENCES public.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.programactivities
    ADD CONSTRAINT programactivities_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.programactivities
    ADD CONSTRAINT programactivities_program_id_fkey FOREIGN KEY (program_id)
    REFERENCES public.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.programs
    ADD CONSTRAINT programs_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.programs
    ADD CONSTRAINT programs_guide_leader_fkey FOREIGN KEY (guide_leader)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.programs
    ADD CONSTRAINT programs_program_type_fkey FOREIGN KEY (program_type)
    REFERENCES public.types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_program_id_fkey FOREIGN KEY (program_id)
    REFERENCES public.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT fk_team FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT fk_company FOREIGN KEY (company_id)
    REFERENCES public.company (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.temporary_access_tokens
    ADD CONSTRAINT temporary_access_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;