# backend/scripts/dump_schema.py
"""
Regenerate schema.sql from a database, so it stops drifting from the migrations.

Run this whenever a migration lands. schema.sql is what bootstrap_schema.py uses to stand up a
brand-new database (`alembic upgrade head` cannot do it alone -- see that module), so a stale
dump means new environments come up with a schema nobody is actually running.

The previous dump was produced by reflecting the database through SQLAlchemy, because pg_dump was
not available on the machine that made it. That cost three things:

  * no CREATE TYPE at all, so the five enums the tables depend on were simply missing
  * tables emitted in reflection order rather than dependency order, so a straight run failed on
    forward references
  * no record of which migration the dump corresponded to

pg_dump has none of those problems. This script drives it, adds a header naming the Alembic
revision the source database is at, and writes the result to schema.sql.

Usage:
    python -m scripts.dump_schema                 # dump the database in DATABASE_URL
    python -m scripts.dump_schema --check         # fail if schema.sql is out of date (for CI)
    python -m scripts.dump_schema --from-scratch  # build a pristine DB at head, dump that
"""
from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys
import tempfile
from urllib.parse import urlparse

from sqlalchemy import create_engine, text

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
BACKEND_DIR = pathlib.Path(__file__).resolve().parents[1]
SCHEMA_SQL = REPO_ROOT / "schema.sql"

REVISION_MARKER = "-- Alembic revision:"


def libpq_url(sqlalchemy_url: str) -> str:
    """postgresql+psycopg2://... -> postgresql://..., which is what pg_dump understands."""
    return re.sub(r"^postgresql\+\w+://", "postgresql://", sqlalchemy_url)


def current_revision(database_url: str) -> str:
    engine = create_engine(database_url, future=True)
    try:
        with engine.connect() as conn:
            row = conn.execute(text("SELECT version_num FROM alembic_version")).first()
            return row[0] if row else "unknown"
    finally:
        engine.dispose()


def run_pg_dump(database_url: str) -> str:
    result = subprocess.run(
        [
            "pg_dump",
            "--schema-only",
            "--no-owner",
            "--no-acl",
            "--no-comments",
            # Deliberately NOT --schema=public. Restricting to a schema makes pg_dump skip
            # CREATE EXTENSION, and the column defaults call public.uuid_generate_v4(), so the
            # restore dies on the first table with `function ... does not exist`. The database
            # only has the public schema anyway, so the unrestricted dump is the same objects
            # plus the extensions they depend on.
            libpq_url(database_url),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"pg_dump failed:\n{result.stderr}")
    return result.stdout


def build_header(revision: str) -> str:
    return (
        "-- Outdaxius schema dump\n"
        "-- Generated by scripts/dump_schema.py (pg_dump --schema-only).\n"
        "-- Regenerate this whenever a migration lands:  python -m scripts.dump_schema\n"
        "--\n"
        "-- This file is the starting point for a brand-new database: `alembic upgrade head`\n"
        "-- alone cannot build one, because 0000_baseline is a no-op standing for a schema that\n"
        "-- already existed. See scripts/bootstrap_schema.py.\n"
        f"{REVISION_MARKER} {revision}\n"
        "\n"
    )


def strip_volatile(sql: str) -> str:
    """Make the dump reproducible, directly runnable, and executable without psql.

    Three transformations, each for a concrete reason:

    * Drop the version banner and timestamp, so an unchanged schema produces an identical file
      and `--check` can be trusted.
    * Drop \\restrict / \\unrestrict. pg_dump 16.13+ wraps its output in these, but they are psql
      META-COMMANDS: any tool that talks to Postgres directly (bootstrap_schema.py, the test
      fixtures) chokes on them. They also embed a fresh random nonce every run, which alone would
      make the file differ on every regeneration.
    * Make CREATE SCHEMA public idempotent. Postgres creates `public` with the database, so the
      dump's bare CREATE SCHEMA aborts a restore into a normal empty database -- exactly the case
      this file exists to serve.
    """
    lines = []
    for line in sql.splitlines():
        if line.startswith(("-- Dumped ", "-- PostgreSQL database dump")):
            continue
        if line.startswith(("\\restrict", "\\unrestrict")):
            continue
        if line.strip() == "CREATE SCHEMA public;":
            line = "CREATE SCHEMA IF NOT EXISTS public;"
        lines.append(line)
    return "\n".join(lines).strip() + "\n"


def build_pristine_database() -> str:
    """Create a throwaway database, bring it to head, and return its URL.

    Dumping a working database risks capturing whatever hand-edits it has accumulated; this makes
    the dump a function of the migrations alone.
    """
    from app.db.config import DATABASE_URL

    parsed = urlparse(libpq_url(DATABASE_URL))
    tmp_name = f"outdaxius_schemagen_{os.getpid()}"
    admin_url = f"postgresql://{parsed.netloc}/postgres"

    engine = create_engine(admin_url, future=True, isolation_level="AUTOCOMMIT")
    with engine.connect() as conn:
        conn.execute(text(f'DROP DATABASE IF EXISTS "{tmp_name}"'))
        conn.execute(text(f'CREATE DATABASE "{tmp_name}"'))
    engine.dispose()

    target = f"postgresql+psycopg2://{parsed.netloc}/{tmp_name}"
    env = {**os.environ, "DATABASE_URL": target}
    subprocess.run(
        [sys.executable, "-m", "scripts.bootstrap_schema"],
        cwd=BACKEND_DIR, env=env, check=True, capture_output=True,
    )
    return target


def drop_database(database_url: str) -> None:
    parsed = urlparse(libpq_url(database_url))
    name = parsed.path.lstrip("/")
    engine = create_engine(
        f"postgresql://{parsed.netloc}/postgres", future=True, isolation_level="AUTOCOMMIT"
    )
    with engine.connect() as conn:
        conn.execute(text(f'DROP DATABASE IF EXISTS "{name}"'))
    engine.dispose()


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate schema.sql from a database.")
    parser.add_argument(
        "--from-scratch",
        action="store_true",
        help="Build a throwaway database from the migrations and dump that, so the output "
             "depends on the migrations alone rather than on the state of a working database.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if schema.sql differs from what the migrations produce. For CI. "
             "Implies --from-scratch: comparing against a working database would just report "
             "whatever hand-edits it has picked up.",
    )
    args = parser.parse_args()

    from_scratch = args.from_scratch or args.check

    temp_db = None
    try:
        if from_scratch:
            temp_db = build_pristine_database()
            database_url = temp_db
        else:
            from app.db.config import DATABASE_URL

            database_url = DATABASE_URL

        revision = current_revision(database_url)
        content = build_header(revision) + strip_volatile(run_pg_dump(database_url))

        if args.check:
            existing = SCHEMA_SQL.read_text(encoding="utf-8") if SCHEMA_SQL.exists() else ""
            if existing != content:
                print(
                    "schema.sql is out of date. Regenerate it with:\n"
                    "  python -m scripts.dump_schema --from-scratch",
                    file=sys.stderr,
                )
                return 1
            print(f"schema.sql is up to date (revision {revision}).")
            return 0

        SCHEMA_SQL.write_text(content, encoding="utf-8")
        print(f"Wrote {SCHEMA_SQL} at revision {revision} ({len(content.splitlines())} lines).")
        return 0
    finally:
        if temp_db:
            drop_database(temp_db)


if __name__ == "__main__":
    raise SystemExit(main())
